/*CRIA PROCEDURE PARA AUMENTTAS VALOR DE VENDA EXATAMENTE*/
SET TERM ^ ;
CREATE PROCEDURE P_AUMENTA_VALOR_EXATO (
    P_ID_PRODUTO integer,
    P_VALMAIS float )
AS
BEGIN
  /* ATUALIZA O VALOR DE VENDA*/ 
  UPDATE PRODUTO
  SET PRODUTO.VL_VENDA = PRODUTO.VL_VENDA + :P_VALMAIS
  WHERE PRODUTO.ID_PRODUTO= :P_ID_PRODUTO;
END^
SET TERM ; ^


/*CRIA PROCEDURE PARA DIMINUIR VALOR DE VENDA EXATAMENTE*/
SET TERM ^ ;
CREATE PROCEDURE P_DIMINUI_VALOR_EXATO (
    P_ID_PRODUTO integer,
    P_VALMENOS float )
AS
BEGIN
  /* ATUALIZA O VALOR DE VENDA*/ 
  UPDATE PRODUTO
  SET PRODUTO.VL_VENDA = PRODUTO.VL_VENDA - :P_VALMENOS
  WHERE PRODUTO.ID_PRODUTO= :P_ID_PRODUTO;
END^
SET TERM ; ^
