/* cria a procedure para amentar o valor de venda dos produtos */
SET TERM ^ ;
CREATE PROCEDURE P_AUMENTA_VALOR_VENDA (
    P_ID_PRODUTO Integer,
    P_PORCENTAGEM Float )
AS
BEGIN
  /* ATUALIZA O VALOR DE VENDA*/ 
  UPDATE PRODUTO
  SET PRODUTO.VL_VENDA=PRODUTO.VL_VENDA + ((PRODUTO.VL_VENDA * :P_PORCENTAGEM)/100)
  WHERE PRODUTO.ID_PRODUTO= :P_ID_PRODUTO;
END^
SET TERM ; ^

SELECT * FROM PRODUTO
WHERE PRODUTO.ID_PRODUTO = 1

/*CHAMA PROCEDURE*/
EXECUTE PROCEDURE P_AUMENTA_VALOR_VENDA(1,10);










