--PESQUISA POR FORMA DE PAGAMENTO
SELECT 
      COUNT(A.ID_COMPRA) AS COMPRAS, 
      SUM(A.VALOR) AS VALOR, 
      A.ID_FORMA_PGTO AS ID,
      B.DESCRICAO AS FORMA_PGTO
FROM COMPRA A 
INNER JOIN FORMA_PGTO B ON B.ID_FORMA_PGTO = A.ID_FORMA_PGTO
GROUP BY A.ID_FORMA_PGTO, B.DESCRICAO;
-- ==============================
--FORMA DE PAGAMENTO POR PERIODO
SELECT 
      COUNT(A.ID_COMPRA) AS COMPRAS, 
      SUM(A.VALOR) AS VALOR, 
      A.ID_FORMA_PGTO AS ID,
      B.DESCRICAO AS FORMA_PGTO
FROM COMPRA A 
INNER JOIN FORMA_PGTO B ON B.ID_FORMA_PGTO = A.ID_FORMA_PGTO
WHERE A.CADASTRO BETWEEN '01.01.2022' AND '31.12.2023'
GROUP BY A.ID_FORMA_PGTO, B.DESCRICAO;
--=======================================
--FORMA DE PAGAMENTO
SELECT 
      COUNT(A.ID_VENDA) AS VENDAS, 
      SUM(A.VALOR) AS VALOR, 
      A.ID_FORMA_PGTO AS ID,
      B.DESCRICAO AS FORMA_PGTO
FROM VENDA A 
INNER JOIN FORMA_PGTO B ON B.ID_FORMA_PGTO = A.ID_FORMA_PGTO
GROUP BY A.ID_FORMA_PGTO, B.DESCRICAO;
--=================================
--FORMA DE PAGAMENTO POR PERIODO
SELECT 
      COUNT(A.ID_VENDA) AS VENDAS, 
      SUM(A.VALOR) AS VALOR, 
      A.ID_FORMA_PGTO AS ID,
      B.DESCRICAO AS FORMA_PGTO
FROM VENDA A 
INNER JOIN FORMA_PGTO B ON B.ID_FORMA_PGTO = A.ID_FORMA_PGTO
WHERE A.CADASTRO BETWEEN '01.01.2022' AND '31.12.2023'
GROUP BY A.ID_FORMA_PGTO, B.DESCRICAO;
--====================================
--TOTAL EM COMPRA POR PERIODO AGRUPADO POR FORNECEDOR
SELECT
      COUNT(A.ID_COMPRA),
      SUM(A.VALOR),
      A.ID_FORNECEDOR,
      B.NOME
 FROM COMPRA A
 INNER JOIN FORNECEDOR B
 ON B.ID_FORNECEDOR = A.ID_FORNECEDOR
 WHERE A.CADASTRO BETWEEN '01.01.2022' AND '31.12.2023'
 GROUP BY A.ID_FORNECEDOR, B.NOME;   
 --===================================================
--TOTAL EM VENDA POR PERIODO AGRUPADO POR FORNECEDOR 
 SELECT
      COUNT(A.ID_VENDA),
      SUM(A.VALOR),
      A.ID_CLIENTE,
      B.NOME
 FROM VENDA A
 INNER JOIN CLIENTE B
 ON B.ID_CLIENTE = A.ID_CLIENTE
 WHERE A.CADASTRO BETWEEN '01.01.2022' AND '31.12.2023'
 GROUP BY A.ID_CLIENTE, B.NOME;   
 --===================================================
-- MOSTRAR TOTAL PAGO POR PERIODO AGRUPADO POR FORNECEDOR 
SELECT 
      COUNT(A.ID_COMPRA),
      SUM(A.TOTAL_PAGAR),
      C.ID_FORNECEDOR,
      C.NOME
FROM CONTAS_PAGAR A INNER JOIN COMPRA B ON B.ID_COMPRA = A.ID_COMPRA
INNER JOIN FORNECEDOR C ON C.ID_FORNECEDOR = B.ID_FORNECEDOR
WHERE A.STATUS = 'PAGO'
AND B.CADASTRO BETWEEN '01.01.2022' AND '31.12.2023'
GROUP BY C.ID_FORNECEDOR, C.NOME;
--====================================================
--MOSTRAR TOTAL RECEBIDO AGRUPADO POR CLIENTE EM PERIODO
SELECT 
      COUNT(A.ID_VENDA) AS QTDE_VENDA,
      SUM(A.TOTAL_PAGAR) AS TOTAL_RECEBIDO,
      C.ID_CLIENTE,
      C.NOME
FROM CONTAS_RECEBER A INNER JOIN VENDA B ON B.ID_VENDA = A.ID_VENDA
INNER JOIN CLIENTE C ON C.ID_CLIENTE = B.ID_CLIENTE
WHERE A.STATUS = 'RECEBIDO'
AND B.CADASTRO BETWEEN '01.01.2022' AND '31.12.2023'
GROUP BY C.ID_CLIENTE, C.NOME
ORDER BY C.ID_CLIENTE, C.NOME;
--================================================
--MOSTRAR TOTAL A PAGAR AGRUPADO POR FORNECEDOR EM PERIODO
SELECT 
      COUNT(A.ID_COMPRA) AS QTDE_COMPRA,
      SUM(A.VALOR_PARCELA) AS VALOR_PAGAR,
      C.ID_FORNECEDOR,
      C.NOME
 FROM CONTAS_PAGAR A INNER JOIN COMPRA B ON B.ID_COMPRA = A.ID_COMPRA
 INNER JOIN FORNECEDOR C ON C.ID_FORNECEDOR = B.ID_FORNECEDOR
 WHERE A.STATUS = 'EM ABERTO'
 AND A.DT_VENCIMENTO BETWEEN '01.01.2022' AND '31.12.2023'
 GROUP BY C.ID_FORNECEDOR, C.NOME
 ORDER BY C.ID_FORNECEDOR, C.NOME;
 --=============================================
 --MOSTRAR SALDO A RECEBER AGRUPADO POR CLIENTES EM PERIODO
SELECT 
      COUNT(A.ID_VENDA) AS QTDE_VENDA,
      SUM(A.VALOR_PARCELA) AS VALOR_RECEBER,
      C.ID_CLIENTE,
      C.NOME
 FROM CONTAS_RECEBER A INNER JOIN VENDA B ON B.ID_VENDA = A.ID_VENDA
 INNER JOIN CLIENTE C ON C.ID_CLIENTE = B.ID_CLIENTE
 WHERE A.STATUS = 'EM ABERTO'
 AND A.DT_VENCIMENTO BETWEEN '01.01.2022' AND '31.12.2023'
 GROUP BY C.ID_CLIENTE, C.NOME
 ORDER BY C.ID_CLIENTE, C.NOME;
--===============================================
--RETORNA TOTAL COMPRADO POR MES
SELECT 
      EXTRACT(MONTH FROM A.CADASTRO) AS MES,
      EXTRACT(YEAR FROM A.CADASTRO) AS ANO,
      SUM(A.VALOR) AS VALOR_COMPRA
FROM COMPRA A 
WHERE A.CADASTRO BETWEEN '01.01.2022' AND '31.12.2023'
GROUP BY EXTRACT(MONTH FROM A.CADASTRO), EXTRACT(YEAR FROM A.CADASTRO)
ORDER BY EXTRACT(MONTH FROM A.CADASTRO), EXTRACT(YEAR FROM A.CADASTRO);
--==================================================
--RETORNA TOTAL VENDIDO POR MES
SELECT 
      EXTRACT(MONTH FROM A.CADASTRO) AS MES,
      EXTRACT(YEAR FROM A.CADASTRO) AS ANO,
      SUM(A.VALOR) AS VALOR_VENDA
FROM VENDA A 
WHERE A.CADASTRO BETWEEN '01.01.2022' AND '31.12.2023'
GROUP BY EXTRACT(MONTH FROM A.CADASTRO), EXTRACT(YEAR FROM A.CADASTRO)
ORDER BY EXTRACT(MONTH FROM A.CADASTRO), EXTRACT(YEAR FROM A.CADASTRO);
